POST http://localhost:8080/gestao/create
Content-Type: application/json

{
  "descricao": "Almoço de Segunda",
  "valor":45,
  "categoria":"refeição",
  "email":"v4@gmail.com",
  "data":"2025-06-09"
}


###

POST http://localhost:8080/gestao/create
Content-Type: application/json

{
  "descricao": "Almoço de Terça",
  "valor":30,
  "categoria":"refeição",
  "email":"v4@gmail.com",
  "data":"2025-06-10"
}

###

POST http://localhost:8080/gestao/create
Content-Type: application/json

{
  "descricao": "Cafe de Quarta",
  "valor":15,
  "categoria":"refeição",
  "email":"v4@gmail.com",
  "data":"2025-06-11"
}


### verificar se post OK

GET http://localhost:8080/gestao/v4@gmail.com


###

http://localhost:8080/gestao/performance/sem-paginacao